from django.urls import path
from . import views

urlpatterns = [
    path(r'my/event/<uuid:event_id>', views.list_event_participant, name='list_event_participant'),
    path(r'my/event/', views.list_my_event, name='list_my_event'),
    path(r'event/<uuid:event_id>', views.list_event_participant, name='list_event_participant'),
    path(r'event/<uuid:event_id>/participants/create/', views.participant_create_view, name='participant_create_view'),
    path(r'event/checkinreset/<uuid:event_id>', views.event_checkinreset, name='event_checkinreset'),
    path(r'participant/<uuid:participant_id>/print', views.print_participant_label, name='print_participant_label'),
    path(r'api/participant/<uuid:participant_id>/print', views.print_participant_label_api,
        name='print_participant_label_api'),
    path(r'api/event', views.json_list_public_event, name='json_list_public_event'),
    path(r'api/my/event', views.json_list_my_event, name='json_list_my_event'),
    path(r'api/my/event/<uuid:event_id>', views.json_event_participant, name='json_event_participant'),
    path(r'api/my/event/<uuid:event_id>/stats', views.json_event_stats, name='json_event_stats'),
    path(r'api/print', views.print_raster_file, name='print_raster_file'),
    path(r'api/scan_local_printers', views.api_scan_local_printers, name='api_scan_local_printers'),
    path(r'api/update_printers', views.api_update_printers, name='api_update_printers'),
    path(r'api/checkin', views.api_check_in, name='api_check_in'),
    path(r'api/checkout', views.api_check_out, name='api_check_out'),
    path(r'api/config/load_printers', views.config_load_printers, name='config_load_printers'),
    path('checkin/', views.qrcode_checkin, name='qrcode_checkin'),
    path('register/', views.register, name='register'),
    path('community/', views.community_list, name='community_list'),
    path('community/dashboard/', views.dashboard, name='dashboard'),
    path('community/create/', views.create_community, name='create_community'),
    path('community/<uuid:community_id>/update/', views.update_community, name='update_community'),
    path('community/<uuid:community_id>/deactivate/', views.deactivate_community, name='deactivate_community'),
    path('community/<uuid:community_id>/', views.community_detail, name='community_detail'),
    path(r'logon', views.badgeprint_logon, name='badgeprint_logon'),
    path(r'logoff', views.badgeprint_logoff, name='badgeprint_logoff'),
    path(r'', views.list_all_event, name='list_all_event'),
]
